version: "3"
services:
  mongoauth:
    container_name: mongo-auth
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27027:27017"
  auth:
    container_name: auth-container
    image: node:12
    working_dir: /usr/src/auth-ts
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes: 
      - ./dist/:/usr/src/auth-ts/dist/
      - ./package.json:/usr/src/auth-ts/package.json
    ports: 
      - "7070:7070"
      - "9777:9777"
    links: 
      - mongoauth